Project: Country culture celebration
Irirwanirira/Capstone-project-1 pull request #1
Opened 2022-09-13 23:57 UTC by Irirwanirira

## My PR consists of :

- [ ] Create a home page about using HTML
- [ ] Style both pages by CSS
- [ ] Inserted Feature speakers dynamically
- [ ] Used javaScript for hamburger menu
- [ ] Modified readme.file 
- [ ] Tested linters
- [ ] Deployed the page on GitHub

### [Loom video](https://www.loom.com/share/65f7deef1b134c35ac054aa802790e35)

 ### Thank you for reviewing my project

2022-09-14 01:39 UTC, mgmediaweb requested changes
Hi @Irirwanirira, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![work2](https://user-images.githubusercontent.com/41912912/190033604-c8db8626-b9a1-4d7b-8fff-5d8874c3aa2d.gif)

## Highlights
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Good job following the design. ✔️ 
- Javascript Code works fine. ✔️ 

## Required Changes ♻️
- Kindly, I suggest by convention using the name of the home page as index.html (instead of homePage.html).
- Kindly, I suggest, and for the same reason as above, that your site does not display correctly in GH PAGES.
- Kindly, I suggest you check the link to the homepage (from the About page), it produces an error.
- Kindly, in the partners section I suggest you use a fixed corner rounding, to avoid that the different sizes of the logo change the size of the curve.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- I kindly suggest you use folders to separate your CSS files from the HTML ones.
- I kindly suggest for this type of exercise to use a single CSS file for both pages and always try to reuse the classes in your different HTML files.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 01:39 UTC, mgmediaweb commented on about.html
> +                <a href="#" class="logo"><img id="ineza-logo" src="./image/images.png" alt="ineza">
Kindly, I suggest you indicate the correct page where this link should be directed (index.html)

2022-09-14 01:39 UTC, mgmediaweb commented on about.html
> +                        <a href="" class="nav-link" >news</a>
Kindly, I suggest you not to leave empty links to avoid errors and bad user experiences.

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.html
> +                    <p class="ccc-1">2022 Country culture celebration. Some Right Reserved.</p>
Kindly, I suggest you use the FOOTER semantic tag on both pages of your website.

2022-09-14 01:39 UTC, mgmediaweb commented on about.html
> +        <div class="ccc-right">
Kindly, I suggest you use the FOOTER semantic tag on both pages of your website.

2022-09-14 01:39 UTC, mgmediaweb commented on about.html
> +        </h1>
Kindly, I suggest you use the same H4 tag to close

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.html
> +                        </h4>
Kindly, I suggest for accessibility convention to use the normal order of the titles H1 (Main title), it should be followed by H2, H3, etc. you use H1 and then H4

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.html
> +                    <div class="box-1">
Kindly, I suggest you use the ARTICLE semantic tag, this tag is perfect for posting repetitive notes.

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.html
> +                    <div class="box-1">
Kindly, I suggest you use the ARTICLE semantic tag, this tag is perfect for posting repetitive notes.

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.html
> +                    <div class="box-1">
Kindly, I suggest you use the ARTICLE semantic tag, this tag is perfect for posting repetitive notes.

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.html
> +                    <div class="box-1">
Kindly, I suggest you use the ARTICLE semantic tag, this tag is perfect for posting repetitive notes.

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.css
> +  /* background-color: #d3d3d3; */
Kindly, I suggest you remove the codes that you are not using, that will make your project look cleaner and more understandable for other programmers.

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.css
> +  /* padding: ; */
Kindly, I suggest you remove the codes that you are not using, that will make your project look cleaner and more understandable for other programmers.

2022-09-14 01:39 UTC, mgmediaweb commented on about.html
> +    <title>Document</title>
Kindly, I suggest you indicate the correct title of your web page

2022-09-14 01:39 UTC, mgmediaweb commented on homePage.css
> +@import url("https://fonts.cdnfonts.com/css/cocogoose");
Kindly, you are not currently using this font, it is essential for your titles to look similar to the original design

2022-09-14 01:39 UTC, mgmediaweb commented on about.css
> +@import url("https://fonts.cdnfonts.com/css/cocogoose");
Kindly, you are not currently using this font, it is essential for your titles to look similar to the original design

2022-09-14 11:28 UTC, Ugboaja-Uchechi requested changes
Hi @Irirwanirira , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 11:28 UTC, Ugboaja-Uchechi commented on README.md
> +
- [ ] Like the previous reviewer mentioned and as stated in the project requirement kindly acknowledge the Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07). 🙏

2022-09-14 11:28 UTC, Ugboaja-Uchechi commented on about.html
> +        </h1>
- [ ] As the previous reviewer mentioned kindly close your `h4` tag with a `h4` instead of a `h1` 🙏

2022-09-14 11:28 UTC, Ugboaja-Uchechi commented on about.html
> +    </section>
- [ ] As the previous reviewer mentioned kindly wrap the end of your `about` and `home` page with a `footer` tag instead of a `section` tag this would give a better experience for people who depend on screen readers. 🙏

2022-09-14 12:23 UTC, Irirwanirira commented on about.html
> +    </section>
done

2022-09-14 12:23 UTC, Irirwanirira commented on README.md
> +
done

2022-09-14 12:31 UTC, Irirwanirira commented on homePage.html
> +            <div class="main-program">
done

2022-09-14 12:31 UTC, Irirwanirira commented on homePage.html
> +            <div class="Speakers-in-general">
Did it.

2022-09-14 12:32 UTC, Irirwanirira commented on homePage.html
> +            <div class="CCC">
sure

2022-09-14 12:59 UTC, m05e5 approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Irirwanirira  🔥 

Good job on implementing the required changes. Well Done.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


Now you can merge this branch 🚀 

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

- _Please see comments under this review_

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 12:59 UTC, m05e5 commented on index.html
> +
- [ optional ] Please as mentioned by the previous reviewers, It's very bad practice to close a `h4` tag with a `h1` tag. this is because by doing so, The `h4` stay unclosed and there is an unexpected  `h1` close tag. in HTML it may not show as an error but in any other programming language, it may crash your app. So be vigilant when coding 😄

2022-09-14 13:21 UTC, Irirwanirira commented on index.html
> +
@m05e5 I got confused with which <h4> in the project but I finally got it, thank you for your time.

2022-09-14 13:23 UTC, Irirwanirira commented on index.html
> +
[h4]

2022-09-14 13:23 UTC, merged

2022-09-15 08:46 UTC, m05e5 commented on index.html
> +
Nice 👍